export const SOCKET_UPDATE_CHANNEL = 'SOCKET_UPDATE_CHANNEL';
export const SOCKET_UPDATE_THREAD = 'SOCKET_UPDATE_THREAD';
export const SOCKET_NEW_MESSAGE = 'SOCKET_NEW_MESSAGE';
export const SOCKET_UPDATE_THREAD_HEADER = 'SOCKET_UPDATE_THREAD_HEADER';
export const ADD_TRANSFER_THREAD = 'ADD_TRANSFER_THREAD';
export const SOCKET_UPDATE_CUSTOMER = 'SOCKET_UPDATE_CUSTOMER';
